#!/usr/bin/env python

# script to generate an /etc/hosts file with ipv6 addrs
# for linodes.   This is a workaround for the fact that
# certain utilities are syntactically allergic 
# to addresses with ":" in them.
#
# sys.argv[1] - ansible inventory file generated by linode-launch.py

import sys

with open(sys.argv[1], 'r') as f:
    lines = [ l.strip() for l in f.readlines() ]

groups = {}
for l in lines:
    if l == '':
        pass
    elif l.startswith('[') and l.endswith(']'):
        group_nm = l.split('[')[1].split(']')[0][:-1]
        groups[group_nm] = []
    elif l.__contains__('='):
	a = l.split()[1].split('=')[1]
	hostnm=l.split()[0]
        groups[group_nm].append((hostnm,a))

print('127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4')
print('::1         localhost localhost.localdomain localhost6 localhost6.localdomain6')

for g in groups.keys():
    for (hostnm, a) in groups[g]:
        print('%s %s' % (a, hostnm))
